/********************************************************************
* /rhome/fujigami/retro/lowe/source/macro/src/macroRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /rhome/fujigami/retro/lowe/source/macro/src/macroRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemacroRootDict();
extern void G__cpp_setup_inheritancemacroRootDict();
extern void G__cpp_setup_typetablemacroRootDict();
extern void G__cpp_setup_memvarmacroRootDict();
extern void G__cpp_setup_globalmacroRootDict();
extern void G__cpp_setup_memfuncmacroRootDict();
extern void G__cpp_setup_funcmacroRootDict();
extern void G__set_cpp_environmentmacroRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/rhome/fujigami/retro/lowe/source/macro/include/eventdisplay.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/goodness_data.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/likelihood_direction_data.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/AnalizedData.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/CSearch_range.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/C4Number.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/FileList.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/efficiency.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/HistByTree.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/HistError.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/HistBias.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/AngleRange.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Thitinfo.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/TReconstructdata.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Tfunction.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Tafunction.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Tdistance_function.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Tfdirection.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Tlikelihood.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Ttheta_dir_i.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Ttheta_i_func.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Ttof.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Tfgoodnessdirection.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/TOption_minimize.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Tfgoodness.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/Tfsumgoodness.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/BiasError.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/FileManager.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/AnalizeTag.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/AnalizeManager.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/AnalizeFile.hh"
#include "/rhome/fujigami/retro/lowe/source/macro/include/TNinWater.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__macroRootDictLN_TClass;
extern G__linked_taginfo G__macroRootDictLN_TBuffer;
extern G__linked_taginfo G__macroRootDictLN_TMemberInspector;
extern G__linked_taginfo G__macroRootDictLN_TObject;
extern G__linked_taginfo G__macroRootDictLN_TNamed;
extern G__linked_taginfo G__macroRootDictLN_TCollection;
extern G__linked_taginfo G__macroRootDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__macroRootDictLN_string;
extern G__linked_taginfo G__macroRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_TObjArray;
extern G__linked_taginfo G__macroRootDictLN_TClonesArray;
extern G__linked_taginfo G__macroRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_TArray;
extern G__linked_taginfo G__macroRootDictLN_TArrayD;
extern G__linked_taginfo G__macroRootDictLN_TAttLine;
extern G__linked_taginfo G__macroRootDictLN_TAttFill;
extern G__linked_taginfo G__macroRootDictLN_TAttMarker;
extern G__linked_taginfo G__macroRootDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__macroRootDictLN_TF1;
extern G__linked_taginfo G__macroRootDictLN_TH1D;
extern G__linked_taginfo G__macroRootDictLN_TH1;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__macroRootDictLN_TH2D;
extern G__linked_taginfo G__macroRootDictLN_TArc;
extern G__linked_taginfo G__macroRootDictLN_TPave;
extern G__linked_taginfo G__macroRootDictLN_Eventdisplay;
extern G__linked_taginfo G__macroRootDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__macroRootDictLN_TVector3;
extern G__linked_taginfo G__macroRootDictLN_TLorentzVector;
extern G__linked_taginfo G__macroRootDictLN_goodness_data;
extern G__linked_taginfo G__macroRootDictLN_l_dir_data;
extern G__linked_taginfo G__macroRootDictLN_AnalizedData;
extern G__linked_taginfo G__macroRootDictLN_C4Number;
extern G__linked_taginfo G__macroRootDictLN_CSearch_range;
extern G__linked_taginfo G__macroRootDictLN_TSeqCollection;
extern G__linked_taginfo G__macroRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__macroRootDictLN_FileList;
extern G__linked_taginfo G__macroRootDictLN_efficiency;
extern G__linked_taginfo G__macroRootDictLN_TTree;
extern G__linked_taginfo G__macroRootDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_TH1DByTree;
extern G__linked_taginfo G__macroRootDictLN_TH1DByTreecLcLAxis;
extern G__linked_taginfo G__macroRootDictLN_HistError;
extern G__linked_taginfo G__macroRootDictLN_HistBias;
extern G__linked_taginfo G__macroRootDictLN_AngleRange;
extern G__linked_taginfo G__macroRootDictLN_WCSimRootCherenkovDigiHit;
extern G__linked_taginfo G__macroRootDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_WCSimRootPMT;
extern G__linked_taginfo G__macroRootDictLN_WCSimRootGeom;
extern G__linked_taginfo G__macroRootDictLN_Thitinfo;
extern G__linked_taginfo G__macroRootDictLN_TReconstructhit;
extern G__linked_taginfo G__macroRootDictLN_TReconstructdata;
extern G__linked_taginfo G__macroRootDictLN_vectorlETReconstructhitcOallocatorlETReconstructhitgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlETReconstructhitcOallocatorlETReconstructhitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_TReconstructdata_minimize;
extern G__linked_taginfo G__macroRootDictLN_Tfunction;
extern G__linked_taginfo G__macroRootDictLN_vectorlEThitinfocOallocatorlEThitinfogRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlEThitinfocOallocatorlEThitinfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_Tafunction;
extern G__linked_taginfo G__macroRootDictLN_Tafuncprototype;
extern G__linked_taginfo G__macroRootDictLN_Tdistance_function;
extern G__linked_taginfo G__macroRootDictLN_Tdistance_position_pmt;
extern G__linked_taginfo G__macroRootDictLN_Tdistance_position_retro;
extern G__linked_taginfo G__macroRootDictLN_Tdistance_fly_retro;
extern G__linked_taginfo G__macroRootDictLN_Tfdirection;
extern G__linked_taginfo G__macroRootDictLN_Tfdirprototypenoretro;
extern G__linked_taginfo G__macroRootDictLN_Tfdirprototypeonretro;
extern G__linked_taginfo G__macroRootDictLN_Tfdirbydatanoretro;
extern G__linked_taginfo G__macroRootDictLN_Tfdirbydataonretro;
extern G__linked_taginfo G__macroRootDictLN_Tlikelihood;
extern G__linked_taginfo G__macroRootDictLN_Tlikelihoodnoretro;
extern G__linked_taginfo G__macroRootDictLN_Tlikelihoodonretro;
extern G__linked_taginfo G__macroRootDictLN_Tlikelihoodsum;
extern G__linked_taginfo G__macroRootDictLN_Ttheta_dir_i;
extern G__linked_taginfo G__macroRootDictLN_Ttheta_i_func;
extern G__linked_taginfo G__macroRootDictLN_Ttof;
extern G__linked_taginfo G__macroRootDictLN_Tfgoodnessdirection;
extern G__linked_taginfo G__macroRootDictLN_TOption_minimize;
extern G__linked_taginfo G__macroRootDictLN_Tfgoodness;
extern G__linked_taginfo G__macroRootDictLN_Tfsumgoodness;
extern G__linked_taginfo G__macroRootDictLN_Tfsumgoodnessnoretro;
extern G__linked_taginfo G__macroRootDictLN_Tfsumgoodnesssum;
extern G__linked_taginfo G__macroRootDictLN_BiasError;
extern G__linked_taginfo G__macroRootDictLN_AnalizeTag;
extern G__linked_taginfo G__macroRootDictLN_AnalizeFile;
extern G__linked_taginfo G__macroRootDictLN_vectorlEAnalizeTagcOallocatorlEAnalizeTaggRsPgR;
extern G__linked_taginfo G__macroRootDictLN_vectorlEAnalizeTagcOallocatorlEAnalizeTaggRsPgRcLcLiterator;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlEAnalizeTagcOallocatorlEAnalizeTaggRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_vectorlEAnalizeFilecOallocatorlEAnalizeFilegRsPgR;
extern G__linked_taginfo G__macroRootDictLN_vectorlEAnalizeFilecOallocatorlEAnalizeFilegRsPgRcLcLiterator;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlEAnalizeFilecOallocatorlEAnalizeFilegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_FileManager;
extern G__linked_taginfo G__macroRootDictLN_AnalizeManager;
extern G__linked_taginfo G__macroRootDictLN_maplEstringcOvectorlEAnalizeFilecOallocatorlEAnalizeFilegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEAnalizeFilecOallocatorlEAnalizeFilegRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR;
extern G__linked_taginfo G__macroRootDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroRootDictLN_TNinWater;

/* STUB derived class for protected member access */
typedef vector<AnalizeTag,allocator<AnalizeTag> > G__vectorlEAnalizeTagcOallocatorlEAnalizeTaggRsPgR;
typedef vector<AnalizeFile,allocator<AnalizeFile> > G__vectorlEAnalizeFilecOallocatorlEAnalizeFilegRsPgR;
