#!/bin/bash

outputfile="Minimize_refractive_`date '+%Y%m%d_%H%M%S'`"
conftemp="/home/fujigami/retro/lowe/config/config_Minimize_refractive_template.sh"
confhalf="/home/fujigami/retro/lowe/config/half.sh"
today=$(date)

cp ${conftemp} ${confhalf}
confname="/home/fujigami/retro/lowe/config/${outputfile}.sh"
logname="/raid1/kuzelab/fujigami/log/${outputfile}.log"
jobname="/home/fujigami/retro/lowe/sh/${outputfile}.sh"

infilecsv="${infilehead}.csv"
infileroot="${infilehead}.root"

if [ ! -f $infileroot ];then
    echo $infileroot + "is not exist... exit"
    exit
fi

if [ ! -f $infilecsv ];then
    echo $infilecsv + "is not exist... exit"
    exit
fi

sed -i -e "s!infile!${infileroot}!g" ${confhalf}

cp ${confhalf} ${confname}
echo "# Generated by the script at ${today} from ${conftemp} by $0" >> ${confname}

if [ ! -f $confname ]; then
    echo $confname + " is not exist... exit"
    \rm ${outputfilecsv}
    exit
fi
echo "log of ${outputfile}" > "$logname"
echo '#!/bin/bash' > "$jobname"
echo "cd '$PWD'" >> "$jobname"
echo "source ../../setup.sh" >> "$jobname"
echo "source ../setup.sh" >> "$jobname"
echo "source $confname" >> "$jobname"
echo "../build/Minimize_refractive > "$logname" 2>&1" >> "$jobname"
chmod +x "$jobname"
#qsub -q ${SERVENAME} "$jobname"
bash "$jobname"
