#!/bin/bash

outputfile="Minimize_`date '+%Y%m%d_%H%M%S'`"
outputfilecsv="$HOME/retro/lowe/analizefile/${outputfile}.csv"
outputfileroot="$HOME/retro/lowe/analizefile/${outputfile}.root"
conftemp="$HOME/retro/lowe/config/config_Minimize_template.sh"
confhalf="$HOME/retro/lowe/config/half.sh"
today=$(date)

cp ${conftemp} ${confhalf}
confname="$HOME/retro/lowe/config/${outputfile}.sh"
logname="$HOME/retro/lowe/log/${outputfile}.log"
jobname="$HOME/retro/lowe/sh/${outputfile}.sh"

infilehead=${infilehead%.*}

infilecsv="${infilehead}.csv"
infileroot="${infilehead}.root"

if [ ! -f $infileroot ];then
    echo $infileroot + "is not exist... exit"
    exit
fi

if [ ! -f $infilecsv ];then
    echo $infilecsv + "is not exist... exit"
    exit
fi

echo ${infilecsv} > ${outputfilecsv}

sed -i -e "s!infile!${infileroot}!g" ${confhalf}

echo "MinimizeFunctionName,string,${MinimizeFunctionName}" >> ${outputfilecsv}
sed -i -e "s/minimizefuncname/${MinimizeFunctionName}/g" ${confhalf}

echo "ValueNumber,int,${ValueNumber}" >> ${outputfilecsv}
sed -i -e "s/valuenumber/${ValueNumber}/g" ${confhalf}

echo "MaxFunctionCalls,int,${MaxFunctionCalls}" >> ${outputfilecsv}
sed -i -e "s/maxfunctioncalls/${MaxFunctionCalls}/g" ${confhalf}

echo "MaxIterations,int,${MaxIterations}" >> ${outputfilecsv}
sed -i -e "s/maxiterations/${MaxIterations}/g" ${confhalf}

echo "Tolerance,double,${Tolerance}" >> ${outputfilecsv}
sed -i -e "s/tolerance/${Tolerance}/g" ${confhalf}

for((i=0;i<${ValueNumber};i++))
do
    echo "Step${i},double,${Step[$i]}" >> ${outputfilecsv}
    sed -i -e "s/step${i}/${Step[$i]}/g" ${confhalf}
    echo "Lower${i},double,${Lower[$i]}" >> ${outputfilecsv}
    sed -i -e "s/lower${i}/${Lower[$i]}/g" ${confhalf}
    echo "Upper${i},double,${Upper[$i]}" >> ${outputfilecsv}
    sed -i -e "s/upper${i}/${Upper[$i]}/g" ${confhalf}
done

echo "OuttreeMinimize,string,${OuttreeMinimize}" >> ${outputfilecsv}
sed -i -e "s/outtree/${OuttreeMinimize}/g" ${confhalf}

echo "MinimizeNEvents,int,${MinimizeNEvents}" >> ${outputfilecsv}
sed -i -e "s/nevents/${MinimizeNEvents}/g" ${confhalf}

isexistsamefile=`../build/isexistsamecsv ${outputfilecsv}`
if [ ${isexistsamefile} = "true" ];then
    echo ${outputfilecsv} + "is already exist... exit"
    \rm ${outputfilecsv}
    exit
elif [ ${isexistsamefile} = "false" ];then
    :
else
    echo ${isexistsamefile} + "is not valid... exit"
    cat ${outputfilecsv}
    cat ${confhalf}
    \rm ${outputfilecsv}
    exit
fi

sed -i -e "s!outfile!${outputfileroot}!g" ${confhalf}
cp ${confhalf} ${confname}
echo "# Generated by the script at ${today} from ${conftemp} by $0" >> ${confname}

if [ ! -f $confname ]; then
    echo $confname + " is not exist... exit"
    \rm ${outputfilecsv}
    exit
fi
echo "log of ${outputfile}" > "$logname"
echo '#!/bin/bash' > "$jobname"
echo "cd '$PWD'" >> "$jobname"
echo "source ../../setup.sh" >> "$jobname"
echo "source ../setup.sh" >> "$jobname"
echo "source $confname" >> "$jobname"
echo "(time ../build/Minimize) > "$logname" 2>&1" >> "$jobname"
echo "isseg=\`grep 'segmentation violation' ${logname}\`" >> "$jobname"
echo "if [ -n \"\$isseg\" ];then" >> "$jobname"
echo "   \rm ${outputfilecsv}" >> "$jobname"
echo "   \rm ${outputfileroot}" >> "$jobname"
echo "fi" >> "$jobname"
chmod +x "$jobname"
qsub -q ${SERVENAME} -e /dev/null -o /dev/null "$jobname"
#bash "$jobname"
