#!/bin/bash

outputfile="tof_`date '+%Y%m%d_%H%M%S'`"
outputfilecsv="$HOME/retro/lowe/analizefile/${outputfile}.csv"
outputfileroot="$HOME/retro/lowe/analizefile/${outputfile}.root"
conftemp="$HOME/retro/lowe/config/config_tof_exe_template.sh"
confhalf="$HOME/retro/lowe/config/half.sh"
today=$(date)

cp ${conftemp} ${confhalf}
confname="$HOME/retro/lowe/config/${outputfile}.sh"
logname="$HOME/retro/lowe/log/${outputfile}.log"
jobname="$HOME/retro/lowe/sh/${outputfile}.sh"

infilecsv="${infilehead}.csv"
infileroot="${infilehead}.root"

if [ ! -f $infileroot ];then
    echo $infileroot + "is not exist... exit"
    exit
fi

if [ ! -f $infilecsv ];then
    echo $infilecsv + "is not exist... exit"
    exit
fi

echo ${infilecsv} > ${outputfilecsv}

sed -i -e "s!infile!${infileroot}!g" ${confhalf}

echo "treetype,string,tof" >> ${outputfilecsv}

echo "NWater,double,${NWater}" >> ${outputfilecsv}

sed -i -e "s/nwater/${NWater}/g" ${confhalf}

echo "tofexeversion,int,2" >> ${outputfilecsv}

isexistsamefile=`../build/isexistsamecsv ${outputfilecsv}`
if [ ${isexistsamefile} = "true" ];then
    echo ${outputfilecsv} + "is already exist... exit"
    \rm ${outputfilecsv}
    exit
elif [ ${isexistsamefile} = "false" ];then
    :
else
    echo ${isexistsamefile} + "is not valid... exit"
    \rm ${outputfilecsv}
    exit
fi

sed -i -e "s!outfile!${outputfileroot}!g" ${confhalf}
cp ${confhalf} ${confname}
echo "# Generated by the script at ${today} from ${conftemp} by $0" >> ${confname}

if [ ! -f $confname ]; then
    echo $confname + " is not exist... exit"
    \rm ${outputfilecsv}
    exit
fi
echo "log of ${outputfile}" > "$logname"
echo '#!/bin/bash' > "$jobname"
echo "cd '$PWD'" >> "$jobname"
echo "source ../../setup.sh" >> "$jobname"
echo "source ../setup.sh" >> "$jobname"
echo "source $confname" >> "$jobname"
echo "../build/tof_exe > "$logname" 2>&1" >> "$jobname"
echo "isseg=\`grep 'segmentation violation' ${logname}\`" >> "$jobname"
echo "if [ -n \"\$isseg\" ];then" >> "$jobname"
echo "   \rm ${outputfilecsv}" >> "$jobname"
echo "   \rm ${outputfileroot}" >> "$jobname"
echo "fi" >> "$jobname"
chmod +x "$jobname"
qsub -q ${SERVENAME} "$jobname"
